### ISSUE TITLE
`array.includes` is undefined in non-ES2015 environments

### ISSUE THREAD

**Issue by pmalouin** [seegno/bookshelf-json-columns#28]
Trying out the new version 1.2.0, an error is thrown because the `includes` array instance method is not defined (it is new in ES2015). I'm using node version 4.5.0 (where this ES2015 feature is missing):

```
TypeError: _this3.jsonColumns.includes is not a function
    at /opt/bitbe/node_modules/bookshelf-json-columns/dist/index.js:100:32
    at Array.forEach (native)
    at save (/opt/bitbe/node_modules/bookshelf-json-columns/dist/index.js:99:31)
    ...
```
You could maybe rely on the [lodash.includes module](https://www.npmjs.com/package/lodash.includes), or the [array-includes module](https://www.npmjs.com/package/array-includes) or simply work around bringing an additional dependency by using `array.indexOf`.

**Comment by ricardogama** [comment]
@pmalouin Thanks for the report! A fix was released as [1.2.1](https://github.com/seegno/bookshelf-json-columns/releases/tag/1.2.1).
