### ISSUE TITLE
Unable to get plugin working

### ISSUE THREAD

**Issue by jamesdixon** [seegno/bookshelf-json-columns#6]
Hi - for some reason I'm unable to get the plugin to work with my current configuration. I set some breakpoints through the plugin code, but nothing is ever triggered. Here's how I'm attempting to use it:

```javascript
// bookshelf.js - bookshelf config file
let knexConfig = require('../knexfile');
let config = require('./default');

// initialize bookshelf and knex
let knex = require('knex')(knexConfig[config.environment]);
let bookshelf = require('bookshelf')(knex);

// add 3rd party plugins
let jsonColumns = require('bookshelf-json-columns');


// load plugins
bookshelf.plugin('registry');
bookshelf.plugin('visibility');
bookshelf.plugin(jsonColumns);

module.exports = bookshelf;
```

```javascript
const _ = require('lodash'),
  Bookshelf = require('../config/bookshelf'),
  BaseModel = require('./base'),
  bcrypt = require('bcrypt'),
  Joi = require('joi'),
  Promise = require('bluebird'),
  scopes = require('../utils/auth/scopes'),
  GIS = require('knex-postgis')(Bookshelf.knex);

var User = BaseModel.extend({

  //////////////////////////////////////
  // PLUGIN CONFIGURATION
  //////////////////////////////////////

  jsonColumns: ['address', 'phoneNumbers', 'secondaryContactInfo'],
  hidden: ['password'],

  //////////////////////////////////////
  // INSTANCE PROPERTIES
  //////////////////////////////////////

  tableName: 'user',

  //////////////////////////////////////
  // VALIDATIONS
  //////////////////////////////////////

  schema: Joi.object().keys({
    firstName: Joi.string(),
    lastName: Joi.string(),
    email: Joi.string().email(),
    password: Joi.string().regex(/[a-zA-Z0-9]{3,30}/).allow(null),
    address: Joi.object(),
    geocodedAddress: Joi.allow(),
    phoneNumbers: Joi.array().items(Joi.object()).allow(null),
    secondaryContactInfo: Joi.object(),
    active: Joi.boolean(),
    archived: Joi.boolean(),
    createdAt: Joi.allow(),
    updatedAt: Joi.allow()
  })

  ....

});

module.exports = Bookshelf.model('User', User);
```

I'm running Bookshelf 0.9.1 and Knex 0.9.0. 

Thanks!

**Comment by ricardogama** [comment]
Hi @jamesdixon. Your configuration seems to be correct, are you debugging the `dist/index.js` file?

**Comment by jamesdixon** [comment]
Hi @ricardogama. Yes, I am. I've set breakpoints within the `initialize` function, but nothing is ever triggered. I tried wiping my `node_modules/` folder and reinstalling, but unfortunately I'm not having any luck.

**Comment by jamesdixon** [comment]
@ricardogama I was inspired by your plugin and had decided to mimick something similar for encrypting and decrypting specific model columns. That said, using a similar setup, I wasn't able to hit any breakpoints in my code. I became curious and decided to try adding a `constructor` method as done in the `visibility` plugin and I was able to hit a breakpoint in that method. I'm just unable to hit anything within the `initialize` method. I'm assuming this can be overridden?

**Comment by jamesdixon** [comment]
Looking at the docs, that method can certainly be overridden. I'll keep digging!

**Comment by ricardogama** [comment]
@jamesdixon The first thing I tried to do when you created the issue was to use it along the plugins in your example, and it worked fine. So I'm suspicious that the problem is in your `BaseModel`, if you defined an `initialize` method you must be careful to extend it and not override it, doing something like this:

```js
/**
 * Module dependencies.
 */

const bookshelf = require('../config/bookshelf'),

// Model prototype.
const Model = bookshelf.Model.prototype;

/**
 * Export `BaseModel`.
 */

module.exports = bookshelf.Model.extend({
  initialize() {
    // Do your stuff.
    
    return Model.initialize.apply(this, arguments);
  }
});
```

Let me know if that works.

**Comment by jamesdixon** [comment]
@ricardogama that did it! Thank you and sorry if I sent you down the rabbit hole. Learn something new every day :+1:

**Comment by jamesdixon** [comment]
also, unrelated, but what's the process for compiling down your es6 version of the library to what's in the `dist` directory? is that done via Babel?

**Comment by jamesdixon** [comment]
nevermind - I see how it's done now in your `package.json`. Thanks again.

**Comment by ricardogama** [comment]
No problem at all, my pleasure to help!
