### ISSUE TITLE
Supporting JSON Arrays

### ISSUE THREAD

**Issue by jamesdixon** [seegno/bookshelf-json-columns#7]
Me again :)

I came across an issue where inserting an array of JSON objects fails into Postgres fails. I tracked it down to Postgres not liking that the array is part of the string. 

```javascript
[
  { key: value },
  { key: value }
]
```

```javascript
// stringified
"[{"key":"value"},{"key":"value"}]"
```

Postgres wants it like so:

```javascript
[{"key":"value"},{"key":"value"}]
```

I can submit a PR to fix, but wasn't sure if this something that should only be done when using the Postgres client in Bookshelf.

Thoughts?

**Comment by jamesdixon** [comment]
Postgres will also accept an object with its root element as an array.

**Comment by jamesdixon** [comment]
Ok, apologies for the issue. It appears the whole reason to stringify the data beforehand is to avoid a design decision in `node-pg` that converts arrays to objects. This may end up being a KNEX issue, but just going explain it here just in case you've run into the issue. If not, let me know and I can move the issue elsewhere.

I'm attempting to insert an array of JSON objects into a JSONB column in postgres. The data looks like this after going through your plugin:

```javascript
"[{"number":"(555) 555-1212","type":"home"},{"number":"(555) 555-1212","type":"mobile"},{"number":"(555) 555-1212","type":"work"}]"
```
I added the following to debug the query being run:

```javascript
knex.on('query', function(data) { console.log(data) })
```

In my console, I see the following output:

![image](https://cloud.githubusercontent.com/assets/110114/11947140/20d7d262-a820-11e5-8c86-9f85c7037a0c.png)

Which results in the following error:

```javascript
{
	"msec": 63700.382493019104,
	"error": "update \"user\" set \"address\" = $1, \"email\" = $2, \"first_name\" = $3, \"last_name\" = $4, \"phone_numbers\" = $5, \"secondary_contact_info\" = $6, \"updated_at\" = $7 where \"id\" = $8 - invalid input syntax for type json",
	"data": {
		"name": "error",
		"length": 195,
		"severity": "ERROR",
		"code": "22P02",
		"detail": "Expected \":\", but found \",\".",
		"where": "JSON data, line 1: ...\"number\\\":\\\"(555) 555-1212\\\",\\\"type\\\":\\\"home\\\"}\",...",
		"file": "json.c",
		"line": "1140",
		"routine": "report_parse_error",
		"isBoom": true,
		"isServer": true,
		"data": null,
		"output": {
			"statusCode": 500,
			"payload": {
				"statusCode": 500,
				"error": "Internal Server Error",
				"message": "An internal server error occurred"
			},
			"headers": {}
		}
	}
}
```

It appears Knex or possibly Bookshelf is adding a bunch of escape characters to the `phoneNumbers` string that was output from your plugin.

Am i missing something here?

Thanks again.

**Comment by ricardogama** [comment]
Hey @jamesdixon, sorry for the delay but I've been on vacation. It seems that the values are being stringified more than once, or are not being parsed after saving. So I guess the `saved` hook from the plugin is not being executed or you are stringifying not parse back elsewhere. Did you solve the problem?

**Comment by jamesdixon** [comment]
@ricardogama no worries at all! Yes, I tracked the issue back to the array being stringified twice. Thanks for the response. Happy New Year!

**Comment by ricardogama** [comment]
Nice to know you worked it out, James. Thanks and likewise!

**Comment by jamesdixon** [comment]
@ricardogama I know this is an old issue, but I'm running into the same issue with JSON arrays. Was curious if you had any problems with this?

**Comment by jamesdixon** [comment]
This appears to be a Bookshelf issue. If I use Knex to insert a JSON array, things work fine. Somewhere in the Bookshelf code, it appears that is stringifying the array again. Given that you are a contributor to the Bookshelf project, do you have any idea where this might be happening?

**Comment by ricardogama** [comment]
@jamesdixon Hey, sorry for the delay. I'll take a look into this, can you tell what client and bookshelf & knex versions you're using? I'll take a look into this.

**Comment by jamesdixon** [comment]
@ricardogama no worries!

I'm using Bookshelf v0.10 and Knex v0.11.9.

I [opened an issue](https://github.com/tgriesser/bookshelf/issues/1328) in the Bookshelf repo as I'm fairly certain that's where the problem resides.

**Comment by ricardogama** [comment]
@jamesdixon I'm tracking the issue, but what client are you using and what version, MySQL?

**Comment by jamesdixon** [comment]
Postgres 9.5

**Comment by jamesdixon** [comment]
@ricardogama were you ever able to reproduce this issue?

**Comment by ricardogama** [comment]
@jamesdixon Sorry for the delay. If you're using `save` with the `patch` option that might be the problem, I'll investigate.

**Comment by ricardogama** [comment]
@jamesdixon Can you try the **feature/update-with-patch-option** and check if the your issue get fixed?

**Comment by jamesdixon** [comment]
@ricardogama I'll give it a shot. Thank you!

**Comment by dpiccone** [comment]
Hi guys, I have the same issue here, using bookshelf 0.10 and Postgres 9.5
A simple schema where `profile_parts` is a JSON column, saving this values in there 

```
profileParts: [ { type: 'PROFILE', value: { link: 'https://foo.bar', image: testImage.id } } ]
```

produces this query 

```
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: 
   [ '2016-08-26T11:23:12.485+02:00',
     'USD',
     'XXXXX',
     '{"{\\"type\\":\\"PROFILE\\",\\"value\\":{\\"link\\":\\"https://foo.bar\\",\\"image\\":\\"70d0d7e0-e0ca-45b5-be48-252d9623b9e8\\"}}"}',
     '123',
     '2016-08-26T11:23:12.485+02:00',
     'XXXX1',
     'XXXX' ],
  __knexQueryUid: '70b1c370-861f-46eb-b943-9ca318777d72',
  sql: 'insert into "vendors" ("created_at", "currency", "name", "profile_parts", "rate", "updated_at", "user_id", "verification_state") values (?, ?, ?, ?, ?, ?, ?, ?) returning "id"',
  returning: 'id' }
```

The value is not just escaped but the wrapping `[...]` are replaced with `{...}`

and I got the same error `invalid input syntax for type json'`
